### ISSUE TITLE
数据集

### ISSUE THREAD

**Issue by nxt2045** [JohnnyY8/Domain-Adversarial#1]
请问getData中.npy文件是怎么处理得到的呀

**Comment by JohnnyY8** [comment]
@isnxt 您好。还不是很明白您的问题，可以具体一点吗？

**Comment by nxt2045** [comment]
请问您在README中提到的数据集是 https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE92742 网站中的哪个呢? 请问是level4数据集么

**Comment by JohnnyY8** [comment]
@isnxt 您好。
我是负责模型的搭建和训练的，数据处理的部分由本文的共一作者Song He负责，这是他的邮箱“809848790@qq.com”，若有关于数据集和预处理的问题，欢迎咨询他，我相信他会及时帮助您解答的。

**Comment by nxt2045** [comment]
好的谢谢您
